Python/JHS/main_app/exam/routes.py
from decimal import Subnormal
from logging import RootLogger
from main_app import db

#   importing basic flask module
from flask import render_template
from flask import Blueprint
from flask import request
from flask import redirect
from flask import flash
from flask import url_for
from flask import jsonify

from main_app.exam.forms import AddExamForm
from main_app.exam.forms import AddExamSubjectForm 
from main_app.exam.forms import AddStudentResultForm 

from main_app.models import Exam
from main_app.models import ExamSubject

#   initializing blueprint
exam = Blueprint('exam', __name__)


#   ADD EXAM 
@exam.route('/exam/add/', methods=['GET','POST'])
def addexam():
    form = AddExamForm()
    exams = Exam.query.all()
    if form.validate_on_submit():
        exam = Exam(exam_name=form.exam_name.data)
        db.session.add(exam)
        db.session.commit()
        flash('Exam added successfuylly ✔', 'success')
        return redirect(url_for('exam.addexam'))

    return render_template('exam/addexam.html', form=form, exams=exams)

@exam.route("/exam/<int:exam_id>/delete/", methods=['POST'])
def exam_delete(exam_id):
    exam = Exam.query.get_or_404(exam_id)
    db.session.delete(exam)
    db.session.commit()
    flash('Your post has been deleted! ✔', 'success')
    return redirect(url_for('exam.addexam'))   


#   ADD EXAM SUBJECT
@exam.route('/exam/subject/add/', methods=['GET', 'POST'])
def addexam_subject():
    form = AddExamSubjectForm()
    form.exam.choices = [(exam.id, exam.exam_name) for exam in Exam.query.all()]
    exam_subject = ExamSubject.query.all()
    if form.validate_on_submit():
        subject = ExamSubject(subject=form.exam_subject_name.data.lower(), full_marks=form.full_marks.data, pass_marks=form.pass_marks.data,exam_id=form.exam.data)
        db.session.add(subject)
        db.session.commit()
        flash('Exam Subject added successfuylly ✔', 'success')
        return redirect(url_for('exam.addexam_subject'))

    return render_template('exam/addexamSubject.html', form=form, exam_subject=exam_subject)


@exam.route("/exam/subject/<int:exam_id>/delete/", methods=['POST'])
def exam_subject_delete(exam_id):
    exam = ExamSubject.query.get_or_404(exam_id)
    db.session.delete(exam)
    db.session.commit()
    flash('Your post has been deleted! ✔', 'success')
    return redirect(url_for('exam.addexam_subject'))  


#   ADD STUDENT RESULT
@exam.route('/exam/student/result/', methods=['GET', 'POST'])
def addexam_student_result():
    # THIS METHOD IS NOT WORKING.
    # GOT A NEW IDEA

    # WE SHOULD ADD INDIVIDUAL SUBJECT MARK WITH STUDENT NAME AND ROLL 
    # AND SAVE INTO DATABASE, THEN WE CAN QUERY THEM BY SUBJECT AND MAKE A INDIVIDUAL STUDENT MARKSHEET 



    form = AddStudentResultForm()
    form.exam.choices = [(exam.id, exam.exam_name) for exam in Exam.query.all()]
    form.exam_subject_name.choices = [(examsubj.id, examsubj.subject) for examsubj in ExamSubject.query.all()]
    exam_subject = ExamSubject.query.all()
    totalsubject=7
    if form.validate_on_submit():
        print(f"Student name: {form.student_name.data}")
        print(f"Student Roll: {form.student_roll.data}")
        print(f"Student Class: {form.student_class.data}")
        print(f"Exam: {form.exam.data}")
        for subject in range(totalsubject):
            print(f"Exam subject name: {form.exam_subject_name.data}")
            print(f"Subject full marks: {form.full_marks.data}")
            print(f"Subject grade: {form.grade.data}")
            print(f"Subject Achive mark: {form.achive_mark.data}")
        print(f"Total mark: {form.total_marks.data}")
        print(f"Total achive mark: {form.total_achive_mark.data}")
        print(f"Total achive grade: {form.total_achive_grade.data}")
        print(f"Result note: {form.result_note.data}")
        # single_sub_array = []
        # for subject in range(totalsubject):
        #     subjectobj = {}
        #     subject['subject'] = 
            # subject['']=
            # exam_details = jsonify({'allsubjectresult': subjectArray})
        # subject = ExamSubject(exam_subject=form.exam_subject_name.data, full_marks=form.full_marks.data, pass_marks=form.pass_marks.data,exam_id=form.exam.data)
        # db.session.add(subject)
        # db.session.commit()
        flash('Exam Subject added successfuylly ✔', 'success')
        return redirect(url_for('exam.addexam'))

    return render_template('exam/addexamStudentResult.html', form=form, exam_subject=exam_subject, totalsubject=totalsubject)


@exam.route('/exam/subject/marks/<int:subject_id>/', methods=['GET', 'POST'])
def get_total_marks(subject_id):
    subjects = ExamSubject.query.filter_by(id=subject_id).all()

    subjectArray = []
    
    for subject in subjects:
        subobj = {}
        subobj['id'] = subject.id
        subobj['subject_name'] = subject.subject
        subobj['full_marks'] = subject.full_marks
        subobj['pass_marks'] = subject.pass_marks
        subjectArray.append(subobj)

    return jsonify({'subjects': subjectArray})

Python/JHS/main_app/main/routes.py
#   importing basic flask module
from flask import render_template
from flask import Blueprint

#   initializing blueprint
main = Blueprint('main', __name__)

#   default route
@main.route('/')
def index():
    return render_template('index.html')

#   about route
@main.route('/about')
def about():
    return render_template('about.html', title='About Us')

Python/JHS/main_app/users/routes.py
from flask import render_template,redirect,url_for,Blueprint,request
from flask_login import login_user,current_user,login_required,logout_user
from main_app import db,bcrypt
from main_app.models import User,Notice
from main_app.users.forms import AdmissionForm,LoginForm,LoginFormParents,ApplyParentsForm,ApplyTeacherForm,DemoRegForm

users = Blueprint('users', __name__)


@users.route('/admission', methods=['GET', 'POST'])
def admission():
    form = AdmissionForm()
    return render_template('admission.html', title='Admission', form=form)


@users.route('/parents/apply', methods=['GET', 'POST'])
def apply_parents():
    form = ApplyParentsForm()
    return render_template('apply_parents.html', title='Parents Application', form=form)

@users.route('/teacher/apply', methods=['GET', 'POST'])
def apply_teacher():
    form = ApplyTeacherForm()
    return render_template('apply_teacher.html', title='Teacher Application', form=form)

@users.route('/dashboard')
def dashboard():
    return render_template('dashboard.html', title='Dasboard')


@users.route('/demo/register', methods=['GET', 'POST'])
def demo_register():
    form = DemoRegForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.login'))
    return render_template('demo_register.html', title='Demo Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember_me.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('users.dashboard'))
    return render_template('login.html', title='Login', form=form)


@users.route('/login/parents', methods=['GET', 'POST'])
def login_parents():
    form = LoginFormParents()
    return render_template('login_parents.html', title='Login', form=form)

Python/JHS/main_app/templates/about.html
{% extends 'layout.html' %} {% block body %}

<main>
  <div class="container">
    <h1>About us</h1>
  </div>
</main>

{% endblock %}

Python/JHS/main_app/templates/admission.html
{% extends 'layout.html' %}



{% block additional_title %}
    Admission -
{% endblock %}

{% block body %}

    <main class="bg_gray pt-5 pb-5">

        <h1 class="h1 text-center mb-5"> Admission Form - 2020 </h1>

        <section class="d-flex justify-content-center">

            <form action="" method="post" class="form-large">
                {{ form.hidden_tag() }}


                <div class="row">

                    <!-- father name -->
                    <div class="col-sm-6">
                        {{ form.firstname.label(class="form-label") }}

                        {% if form.firstname.errors %}
                            {{ form.firstname( class="form-control is-invalid" ) }}
                            <div class="invalid-feedback">
                                {% for error in form.firstname.errors %}
                                    <span>  {{ error }}   </span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.firstname(
                                class="form-control",
                                placeholder="First name"
                            ) }}
                        {% endif %}
                    </div>

                    <!-- last name -->
                    <div class="col-sm-6">
                        {{ form.lastname.label(class="form-label") }}

                        {% if form.lastname.errors %}
                            {{ form.lastname( class="form-control is-invalid" ) }}
                            <div class="invalid-feedback">
                                {% for error in form.lastname.errors %}
                                    <span>  {{ error }}   </span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.lastname(
                                class="form-control",
                                placeholder="Lastname"
                            ) }}
                        {% endif %}
                    </div>
                </div>


                <div class="row mt-2">

                    <!-- father name -->
                    <div class="col-sm-6">
                        {{ form.father_name.label(class="form-label") }}

                        {% if form.father_name.errors %}
                            {{ form.father_name( class="form-control is-invalid" ) }}
                            <div class="invalid-feedback">
                                {% for error in form.father_name.errors %}
                                    <span>  {{ error }}   </span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.father_name(
                                class="form-control",
                                placeholder="Father's name"
                            ) }}
                        {% endif %}
                    </div>

                    <!-- mother name -->
                    <div class="col-sm-6">
                        {{ form.mother_name.label(class="form-label") }}

                        {% if form.mother_name.errors %}
                            {{ form.mother_name( class="form-control is-invalid" ) }}
                            <div class="invalid-feedback">
                                {% for error in form.mother_name.errors %}
                                    <span>  {{ error }}   </span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.mother_name(
                                class="form-control",
                                placeholder="Mother's name"
                            ) }}
                        {% endif %}
                    </div>

                </div>


                <div class="row mt-2">

                    <!-- select class -->
                    <div class="col-sm-6">
                        {{ form.applicable_class.label(class="form-label") }}
                        {{ form.applicable_class(class="form-select") }}
                    </div>

                    <!-- phone number -->
                    <div class="col-sm-6">
                        {{ form.phone_number.label(class="form-label") }}

                        {% if form.phone_number.errors %}
                            {{ form.phone_number( class="form-control is-invalid" ) }}
                            <div class="invalid-feedback">
                                {% for error in form.phone_number.errors %}
                                    <span>  {{ error }}   </span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.phone_number(
                                class="form-control",
                                placeholder="Phone Number"
                            ) }}
                        {% endif %}
                    </div>



                </div>


                <div class="row mt-2">

                    <!-- birth cirtificate no -->
                    <div class="col-sm-6">
                        {{ form.birth_cirtificate_no.label(class="form-label") }}

                        {% if form.birth_cirtificate_no.errors %}
                            {{ form.birth_cirtificate_no( class="form-control is-invalid" ) }}
                            <div class="invalid-feedback">
                                {% for error in form.birth_cirtificate_no.errors %}
                                    <span>  {{ error }}   </span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.birth_cirtificate_no(
                                class="form-control",
                                placeholder="Birth Cirtificate No"
                            ) }}
                        {% endif %}
                    </div>

                    <!-- brith of date -->
                    <div class="col-sm-6">
                        {{ form.birth_date.label(class="form-label") }}

                        {% if form.birth_date.errors %}
                            {{ form.birth_date( class="form-control is-invalid" ) }}
                            <div class="invalid-feedback">
                                {% for error in form.birth_date.errors %}
                                    <span>  {{ error }}   </span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.birth_date(
                                class="form-control",
                                placeholder="DD/MM/YY"
                            ) }}
                        {% endif %}
                    </div>

                </div>


                <div class="row mt-2">

                    <!-- address -->
                    <div class="col-sm-6">
                        {{ form.address.label(class="form-label") }}

                        {{ form.address(
                            class="form-control",
                            placeholder="Address"
                        ) }}
                    </div>

                    <!-- gender -->
                    <div class="col-sm-6">

                        <p class="form-label"> Gender </p>

                        <div class="d-flex align-items-center nobg">
                            <div class="form-check form-control">
                                {{ form.male(class="form-check-input") }}
                                {{ form.male.label(class="form-label") }}
                            </div>

                            <div class="form-check form-control">
                                {{ form.female(class="form-check-input") }}
                                {{ form.female.label(class="form-label") }}
                            </div>
                        </div>

                    </div>

                </div>


                <div class="row mt-2">

                    <!-- email -->
                    <div class="col-sm-6">
                        {{ form.email.label(class="form-label") }}

                        {{ form.email(
                            class="form-control",
                            placeholder="Email Address"
                        ) }}
                    </div>

                    <!-- transportation service -->
                    <div class="col-sm-6">

                        <p class="form-label"> Request for transportation service </p>

                        <div class="d-flex align-items-center nobg">
                            <div class="form-check form-control">
                                {{ form.yes(class="form-check-input") }}
                                {{ form.yes.label(class="form-label") }}
                            </div>

                            <div class="form-check form-control">
                                {{ form.no(class="form-check-input") }}
                                {{ form.no.label(class="form-label") }}
                            </div>
                        </div>

                    </div>

                </div>


                <div class="row mt-2">

                    <!-- photo -->
                    <div class="col-sm-6">
                        {{ form.photo.label(class="form-label") }}
                        {{ form.photo( class="form-control" ) }}
                    </div>

                    <!-- signature -->
                    <div class="col-sm-6">
                        {{ form.signature.label(class="form-label") }}
                        {{ form.signature( class="form-control" ) }}
                    </div>
                </div>

                <div class="row mt-5">

                    <p class="text-break ">
                        I agree all the terms and condition and cirtify that all the information I gave above is true. If the authority find any
                        flase information I will accept any dicision that the authority takes.
                    </p>
                </div>

                <div class="d-flex justify-content-end mt-4 mb-3">
                    {{ form.submit(class="btn btn-lg btn-primary") }}
                </div>

            </form>

        </section>

        </div>

    </main>
{% endblock %}

Python/JHS/main_app/templates/apply_parents.html
{% extends 'layout.html' %}



{% block additional_title %}
    Create Account Parents -
{% endblock %}



{% block additional_link %}
    <!-- <link rel="stylesheet" href=" {{ url_for('static', filename='admission/admission.css') }} "> -->
{% endblock %}



{% block body %}

    <main class="vh100 bg_gray pt-5 pb-5">
    
        <h2 class="h1 text-center mb-5"> Crate Account for Parents </h2>


        <section class="d-flex justify-content-center">
        

            <form action="" method="post" class="form-large">
                {{ form.hidden_tag() }}


                <div class="row">

                    <!-- name -->
                    <div class="col-sm-6">
                        {{ form.name.label(class="form-label") }}

                        {% if form.name.errors %}
                            {{ form.name( class="form-control is-invalid" ) }}
                            <div class="invalid-feedback">
                                {% for error in form.name.errors %}
                                    <span>  {{ error }}   </span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.name(
                                class="form-control",
                                placeholder="Name"
                            ) }}
                        {% endif %}
                    </div>

                    <!-- username -->
                    <div class="col-sm-6">
                        {{ form.username.label(class="form-label") }}

                        {% if form.username.errors %}
                            {{ form.username( class="form-control is-invalid" ) }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>  {{ error }}   </span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.username(
                                class="form-control",
                                placeholder="Username"
                            ) }}
                        {% endif %}
                    </div>
                </div>


                <div class="row mt-2">

                    <!-- phone number -->
                    <div class="col-sm-6">
                        {{ form.phone_number.label(class="form-label") }}

                        {% if form.phone_number.errors %}
                            {{ form.phone_number( class="form-control is-invalid" ) }}
                            <div class="invalid-feedback">
                                {% for error in form.phone_number.errors %}
                                    <span>  {{ error }}   </span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.phone_number(
                                class="form-control",
                                placeholder="Fathername"
                            ) }}
                        {% endif %}
                    </div>

                    <!-- email address -->
                    <div class="col-sm-6">
                        {{ form.email.label(class="form-label") }}

                        {% if form.email.errors %}
                            {{ form.email( class="form-control is-invalid" ) }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>  {{ error }}   </span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.email(
                                class="form-control",
                                placeholder="E-mail"
                            ) }}
                        {% endif %}
                    </div>

                </div>


                <div class="row mt-2">

                    <!-- student name -->
                    <div class="col-sm-6">
                        {{ form.student_name.label(class="form-label") }}
                        
                        {% if form.student_name.errors %}
                        {{ form.student_name( class="form-control is-invalid" ) }}
                        <div class="invalid-feedback">
                            {% for error in form.student_name.errors %}
                                <span>  {{ error }}   </span>
                            {% endfor %}
                        </div>

                        {% else %}
                            {{ form.student_name( 
                                class="form-control",
                                placeholder="Your children's name"
                            ) }}
                        {% endif %}
                    </div>

                    <!-- student class -->
                    <div class="col-sm-6">
                        {{ form.student_class.label(class="form-label") }}

                        {% if form.student_class.errors %}
                            {{ form.student_class( class="form-select is-invalid" ) }}
                            <div class="invalid-feedback">
                                {% for error in form.student_class.errors %}
                                    <span>  {{ error }}   </span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.student_class( class="form-select" ) }}
                        {% endif %}
                    </div>

                </div>


                <div class="row mt-2">

                    <!-- email -->
                    <div class="col-sm-6">
                        {{ form.student_roll.label(class="form-label") }}

                        {{ form.student_roll(
                            class="form-control",
                            placeholder="Student roll"
                        ) }}
                    </div>

                    <!-- photo -->
                    <div class="col-sm-6">
                        {{ form.photo.label(class="form-label") }}
                        {{ form.photo( class="form-control" ) }}
                    </div>

                </div>

                <div class="d-flex justify-content-end mt-4 mb-3">
                    {{ form.submit(class="btn btn-lg btn-primary") }}
                </div>

            </form>

        </section>
        
        </div>
        
    </main>
{% endblock %}

Python/JHS/main_app/templates/apply_teacher.html
{% extends 'layout.html' %}



{% block additional_title %}
    Create Account Parents -
{% endblock %}



{% block additional_link %}
    <!-- <link rel="stylesheet" href=" {{ url_for('static', filename='admission/admission.css') }} "> -->
{% endblock %}


{% block body %}

    <main class="vh100 bg_gray pt-5 pb-5">

        <h2 class="h1 text-center mb-5"> Crate Account for Parents </h2>


        <section class="d-flex justify-content-center">


            <form action="" method="post" class="form-large">
                {{ form.hidden_tag() }}


                <div class="row">

                    <!-- name -->
                    <div class="col-sm-6">
                        {{ form.name.label(class="form-label") }}

                        {% if form.name.errors %}
                            {{ form.name( class="form-control is-invalid" ) }}
                            <div class="invalid-feedback">
                                {% for error in form.name.errors %}
                                    <span>  {{ error }}   </span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.name(
                                class="form-control",
                                placeholder="Name"
                            ) }}
                        {% endif %}
                    </div>

                    <!-- username -->
                    <div class="col-sm-6">
                        {{ form.username.label(class="form-label") }}

                        {% if form.username.errors %}
                            {{ form.username( class="form-control is-invalid" ) }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>  {{ error }}   </span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.username(
                                class="form-control",
                                placeholder="Username"
                            ) }}
                        {% endif %}
                    </div>
                </div>


                <div class="row mt-2">

                    <!-- phone number -->
                    <div class="col-sm-6">
                        {{ form.phone_number.label(class="form-label") }}

                        {% if form.phone_number.errors %}
                            {{ form.phone_number( class="form-control is-invalid" ) }}
                            <div class="invalid-feedback">
                                {% for error in form.phone_number.errors %}
                                    <span>  {{ error }}   </span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.phone_number(
                                class="form-control",
                                placeholder="Fathername"
                            ) }}
                        {% endif %}
                    </div>

                    <!-- email address -->
                    <div class="col-sm-6">
                        {{ form.email.label(class="form-label") }}

                        {% if form.email.errors %}
                            {{ form.email( class="form-control is-invalid" ) }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>  {{ error }}   </span>
                                {% endfor %}
                            </div>

                        {% else %}
                            {{ form.email(
                                class="form-control",
                                placeholder="E-mail"
                            ) }}
                        {% endif %}
                    </div>

                </div>

                <div class="d-flex justify-content-end mt-4 mb-3">
                    {{ form.submit(class="btn btn-lg btn-primary") }}
                </div>

            </form>

        </section>

        </div>

    </main>
{% endblock %}

Python/JHS/main_app/templates/index.html
{% extends 'layout.html' %} {% block help_developer %} {% endblock %} {% block
body %}
<div class="custom_form_center_100vh">
  <div class="container text-center">
    <h1>All these routes are available</h1>

    <div
      class="btn-group btn-group-sm"
      role="group"
      aria-label="Small button group"
    >
      <a href=" {{ url_for('main.index') }} " class="btn btn-secondary">
        Home
      </a>
      <a href=" {{ url_for('users.login') }} " class="btn btn-secondary">
        Login
      </a>
      <a
        href=" {{ url_for('users.login_parents') }} "
        class="btn btn-secondary"
      >
        Parents Login
      </a>
      <a href=" {{ url_for('users.admission') }} " class="btn btn-secondary">
        Admission
      </a>
      <a
        href=" {{ url_for('users.apply_parents') }} "
        class="btn btn-secondary"
      >
        Parents Application Form
      </a>
      <a
        href=" {{ url_for('users.apply_teacher') }} "
        class="btn btn-secondary"
      >
        Teacher Application Form
      </a>
      <a href=" {{ url_for('main.about') }} " class="btn btn-secondary">
        About
      </a>
    </div>

    <br />

    <div
      class="btn-group btn-group-sm mt-3"
      role="group"
      aria-label="Small button group"
    >
      <a href=" {{ url_for('exam.addexam') }} " class="btn btn-secondary">
        Add Exam
      </a>

      <a
        href=" {{ url_for('exam.addexam_subject') }} "
        class="btn btn-secondary"
      >
        Add Exam Subject
      </a>
      <a
        href=" {{ url_for('exam.addexam_student_result') }} "
        class="btn btn-secondary"
      >
        Add Student Result
      </a>
    </div>
  </div>
</div>
{% endblock %}