Python/JHS/main_app/exam/forms.py
from socketserver import DatagramRequestHandler
from tokenize import String
from unittest import result
from wsgiref.validate import validator
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms import TextAreaField
from wtforms import PasswordField
from wtforms import SubmitField
from wtforms import SelectField
from wtforms import BooleanField
from wtforms import IntegerField
from wtforms import FileField

#   wtf validators
from wtforms.validators import DataRequired
from wtforms.validators import Length
from wtforms.validators import Email
from wtforms.validators import EqualTo


class AddExamForm(FlaskForm):
    exam_name = StringField(
        'Subject name',
        validators = [ DataRequired() ]
    )

    submit = SubmitField('Confirm')



class AddExamSubjectForm(FlaskForm):
    exam_subject_name = StringField(
        'Exam Subject name',
        validators = [ DataRequired() ]
    )

    full_marks = StringField(
        'Full Marks',
        validators = [ DataRequired() ]
    )

    pass_marks = StringField(
        'Pass Mark',
        validators = [ DataRequired() ] 
    )

    exam = SelectField(
        'Exam', 
        choices=[],
        validators=[DataRequired()]
    )

    submit = SubmitField('Cofirm')



class AddStudentResultForm(FlaskForm):
    student_name = StringField(
        'Student name'
    )

    student_roll = IntegerField(
        'Student Roll'
    )

    student_class = StringField(
        'Student Class'
    )

    exam = SelectField(
        'Exam', 
        choices=[],
        validators=[DataRequired()]
    )

    exam_subject_name = SelectField(
        'Exam Subject name',
        choices=[],
        validators = [ DataRequired() ]
    )

    full_marks = StringField('Full Marks')

    grade = StringField(
        'Grade'
    )

    achive_mark = StringField(
        'Achive Mark'
    )

    total_marks = StringField(
        'Total Marks'
    )    

    total_achive_mark = StringField(
        'Total Achive Marks'
    )    

    total_achive_grade = StringField(
        'Total Grade'
    )

    result_note = TextAreaField('Result Note')

    submit = SubmitField('Add Result')

Python/JHS/main_app/exam/routes.py
from decimal import Subnormal
from logging import RootLogger
from main_app import db

#   importing basic flask module
from flask import render_template
from flask import Blueprint
from flask import request
from flask import redirect
from flask import flash
from flask import url_for
from flask import jsonify

from main_app.exam.forms import AddExamForm
from main_app.exam.forms import AddExamSubjectForm 
from main_app.exam.forms import AddStudentResultForm 

from main_app.models import Exam
from main_app.models import ExamSubject

#   initializing blueprint
exam = Blueprint('exam', __name__)


#   ADD EXAM 
@exam.route('/exam/add/', methods=['GET','POST'])
def addexam():
    form = AddExamForm()
    exams = Exam.query.all()
    if form.validate_on_submit():
        exam = Exam(exam_name=form.exam_name.data)
        db.session.add(exam)
        db.session.commit()
        flash('Exam added successfuylly ✔', 'success')
        return redirect(url_for('exam.addexam'))

    return render_template('exam/addexam.html', form=form, exams=exams)

@exam.route("/exam/<int:exam_id>/delete/", methods=['POST'])
def exam_delete(exam_id):
    exam = Exam.query.get_or_404(exam_id)
    db.session.delete(exam)
    db.session.commit()
    flash('Your post has been deleted! ✔', 'success')
    return redirect(url_for('exam.addexam'))   


#   ADD EXAM SUBJECT
@exam.route('/exam/subject/add/', methods=['GET', 'POST'])
def addexam_subject():
    form = AddExamSubjectForm()
    form.exam.choices = [(exam.id, exam.exam_name) for exam in Exam.query.all()]
    exam_subject = ExamSubject.query.all()
    if form.validate_on_submit():
        subject = ExamSubject(subject=form.exam_subject_name.data.lower(), full_marks=form.full_marks.data, pass_marks=form.pass_marks.data,exam_id=form.exam.data)
        db.session.add(subject)
        db.session.commit()
        flash('Exam Subject added successfuylly ✔', 'success')
        return redirect(url_for('exam.addexam_subject'))

    return render_template('exam/addexamSubject.html', form=form, exam_subject=exam_subject)


@exam.route("/exam/subject/<int:exam_id>/delete/", methods=['POST'])
def exam_subject_delete(exam_id):
    exam = ExamSubject.query.get_or_404(exam_id)
    db.session.delete(exam)
    db.session.commit()
    flash('Your post has been deleted! ✔', 'success')
    return redirect(url_for('exam.addexam_subject'))  


#   ADD STUDENT RESULT
@exam.route('/exam/student/result/', methods=['GET', 'POST'])
def addexam_student_result():
    # THIS METHOD IS NOT WORKING.
    # GOT A NEW IDEA

    # WE SHOULD ADD INDIVIDUAL SUBJECT MARK WITH STUDENT NAME AND ROLL 
    # AND SAVE INTO DATABASE, THEN WE CAN QUERY THEM BY SUBJECT AND MAKE A INDIVIDUAL STUDENT MARKSHEET 



    form = AddStudentResultForm()
    form.exam.choices = [(exam.id, exam.exam_name) for exam in Exam.query.all()]
    form.exam_subject_name.choices = [(examsubj.id, examsubj.subject) for examsubj in ExamSubject.query.all()]
    exam_subject = ExamSubject.query.all()
    totalsubject=7
    if form.validate_on_submit():
        print(f"Student name: {form.student_name.data}")
        print(f"Student Roll: {form.student_roll.data}")
        print(f"Student Class: {form.student_class.data}")
        print(f"Exam: {form.exam.data}")
        for subject in range(totalsubject):
            print(f"Exam subject name: {form.exam_subject_name.data}")
            print(f"Subject full marks: {form.full_marks.data}")
            print(f"Subject grade: {form.grade.data}")
            print(f"Subject Achive mark: {form.achive_mark.data}")
        print(f"Total mark: {form.total_marks.data}")
        print(f"Total achive mark: {form.total_achive_mark.data}")
        print(f"Total achive grade: {form.total_achive_grade.data}")
        print(f"Result note: {form.result_note.data}")
        # single_sub_array = []
        # for subject in range(totalsubject):
        #     subjectobj = {}
        #     subject['subject'] = 
            # subject['']=
            # exam_details = jsonify({'allsubjectresult': subjectArray})
        # subject = ExamSubject(exam_subject=form.exam_subject_name.data, full_marks=form.full_marks.data, pass_marks=form.pass_marks.data,exam_id=form.exam.data)
        # db.session.add(subject)
        # db.session.commit()
        flash('Exam Subject added successfuylly ✔', 'success')
        return redirect(url_for('exam.addexam'))

    return render_template('exam/addexamStudentResult.html', form=form, exam_subject=exam_subject, totalsubject=totalsubject)


@exam.route('/exam/subject/marks/<int:subject_id>/', methods=['GET', 'POST'])
def get_total_marks(subject_id):
    subjects = ExamSubject.query.filter_by(id=subject_id).all()

    subjectArray = []
    
    for subject in subjects:
        subobj = {}
        subobj['id'] = subject.id
        subobj['subject_name'] = subject.subject
        subobj['full_marks'] = subject.full_marks
        subobj['pass_marks'] = subject.pass_marks
        subjectArray.append(subobj)

    return jsonify({'subjects': subjectArray})

Python/JHS/main_app/templates/exam/addexam.html
{% extends 'layout.html' %}

<!--  -->
{% block body %}

<main>
  <div class="container my-3">
    <div class="d-flex">
      <h2>Exam Center</h2>

      <span class="align-self-center ms-3">
        <button
          type="button"
          class="btn btn-outline-dark"
          data-bs-toggle="modal"
          data-bs-target="#addExamModal"
        >
          Add new exam
        </button>
      </span>
    </div>
    <!-- Modal -->
    <div
      class="modal fade"
      id="addExamModal"
      tabindex="-1"
      aria-labelledby="addExamModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog">
        <div class="modal-content">
          <!-- MODAL HADER -->
          <div class="modal-header">
            <h3 class="modal-title fs-5" id="addExamModalLabel">
              Add new exam
            </h3>
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="modal"
              aria-label="Close"
            ></button>
          </div>

          <form action="" method="POST">
            <!-- MODAL BODY -->
            <div class="modal-body">
              {{ form.hidden_tag() }}
              <div class="mb-3">
                {{ form.exam_name( class="form-control", placeholder="Exam name"
                ) }}
              </div>
            </div>

            <!-- MODAL FOOTER -->
            <div class="modal-footer">
              <button
                type="button"
                class="btn btn-sm btn-outline-secondary"
                data-bs-dismiss="modal"
              >
                Close
              </button>

              {{ form.submit(class="btn btn-sm btn-dark") }}
            </div>
          </form>
        </div>
      </div>
    </div>

    <div class="mt-5">
      <h3>Available exam</h3>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>#</th>
            <th>Exam Name</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for exam in exams %}
          <tr>
            <th>{{ exam.id }}</th>
            <td>{{ exam.exam_name }}</td>
            <td>
              <form
                action="{{ url_for('exam.exam_delete', exam_id=exam.id) }}"
                method="POST"
              >
                <button class="btn btn-sm btn-danger" type="submit">
                  Delete
                </button>
              </form>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</main>

{% endblock %}

Python/JHS/main_app/templates/exam/addexamSubject.html
{% extends 'layout.html' %}

<!--  -->
{% block body %}
<main>
  <div class="container my-3">
    <div class="d-flex">
      <h1>Exam Center - Subject</h1>

      <span class="align-self-center ms-3">
        <button
          type="button"
          class="btn btn-outline-dark"
          data-bs-toggle="modal"
          data-bs-target="#addExamModal"
        >
          Add new Subject
        </button>
      </span>
    </div>
    <!-- Modal -->
    <div
      class="modal fade"
      id="addExamModal"
      tabindex="-1"
      aria-labelledby="addExamModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog">
        <div class="modal-content">
          <!-- MODAL HADER -->
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="addExamModalLabel">
              Add new subject
            </h1>
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="modal"
              aria-label="Close"
            ></button>
          </div>

          <form action="" method="POST">
            <!-- MODAL BODY -->
            <div class="modal-body">
              {{ form.hidden_tag() }}
              <div class="mb-3">
                {{ form.exam_subject_name( class="form-control",
                placeholder="Exam Subject" ) }}
              </div>

              <div class="mb-3">
                {{ form.full_marks( class="form-control", placeholder="Full
                Marks" ) }}
              </div>

              <div class="mb-3">
                {{ form.pass_marks( class="form-control", placeholder="Pass
                Marks" ) }}
              </div>

              <div class="mb-3">{{ form.exam( class="form-select" ) }}</div>
            </div>

            <!-- MODAL FOOTER -->
            <div class="modal-footer">
              <button
                type="button"
                class="btn btn-sm btn-outline-secondary"
                data-bs-dismiss="modal"
              >
                Close
              </button>

              {{ form.submit(class="btn btn-sm btn-dark") }}
            </div>
          </form>
        </div>
      </div>
    </div>

    <div class="table__container mt-5">
      <h2>Available exam</h2>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Exam Subject</th>
            <th scope="col">Full Marks</th>
            <th scope="col">Pass Marks</th>
            <th scope="col">Exam Name</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          {% for exam in exam_subject %}
          <tr>
            <th scope="row">1</th>
            <td class="text-capitalize">{{ exam.subject }}</td>
            <td>{{ exam.full_marks }}</td>
            <td>{{ exam.pass_marks }}</td>
            <td>{{ exam.exam_name.exam_name }}</td>
            <td>
              <form
                action="{{ url_for('exam.exam_subject_delete', exam_id=exam.id) }}"
                method="POST"
              >
                <button type="submit" class="btn btn-sm btn-danger">
                  Delete
                </button>
              </form>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</main>

{% endblock %}